[programs.localnet]
anchor_client = "CimeoPU3t5FXYJqYCAX1rMZff6BLG4bBKjy68Nh6NV2N"

[programs.devnet]
anchor_client = "CimeoPU3t5FXYJqYCAX1rMZff6BLG4bBKjy68Nh6NV2N"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/PAT/.config/solana/id.json"

[scripts]
# test = "node ./tests/AnchorClient.js"
test = "node ./tests/AnchorDeploy.js"

