[programs.localnet]
anchor_client = "7vdFP5RyHSH1kYFeQpzdsaWda7xw1zEEunWYmmetbLdv"

[programs.devnet]
anchor_client = "7vdFP5RyHSH1kYFeQpzdsaWda7xw1zEEunWYmmetbLdv"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/PAT/.config/solana/id.json"

[scripts]
# test = "node ./tests/AnchorClient.js"
test = "node ./tests/AnchorDeploy.js"

